# version: "3.9"

# services:
#   frontend:
#     build: ./frontend
#     container_name: mern_frontend
#     restart: always
#     ports:
#       - '5173:5173' 

#   backend:
#     build: ./backend
#     container_name: mern_backend
#     env_file:
#       - ./backend/.env
#     restart: always
#     ports:
#       - '5000:5000' 
#     # depends_on:
#     #   - mongo

#   # mongo:
#   #   image: mongo:7
#   #   container_name: mern_mongo
#   #   restart: always
#   #   volumes:
#   #     - mongo_data:/data/db

#   nginx:
#     build: ./nginx
#     container_name: mern_nginx
#     ports:
#       - "80:80"
#     depends_on:
#       - frontend
#       - backend

# volumes:
#   mongo_data:



# version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: mern_frontend
    restart: always
    ports:
      - "5173:5173"

  backend:
    build: ./backend
    container_name: mern_backend
    env_file:
      - ./backend/.env
    restart: always

  nginx:
    build: ./nginx
    container_name: mern_nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
