# version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: mern_frontend
    restart: always
    ports:
      - "5173:5173"

  backend:
    build: ./backend
    container_name: mern_backend
    env_file:
      - ./backend/.env
    restart: always

  nginx:
    build: ./nginx
    container_name: mern_nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
